name: Check Matrix

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        transport: [native, nio]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.2.0
      with:
        java-version: 1.8
    - name: Build with Gradle
# IF WE NEED TO TEST DIFFERENT VERSIONS OF NETTY, WE CAN ADD forceNettyVersion TO THE MATRIX
#      run: ./gradlew check -PforceTransport=${{ matrix.transport }} -PforceNettyVersion=${{ matrix.netty }}
      run: ./gradlew clean check -PforceTransport=${{ matrix.transport }}
    - name: Archive tests output
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: tests_output_${{ matrix.os }}_${{ matrix.transport }}
        path: build/test-results/test/binary/output.bin
